CREATE TABLE STG_FACILITY_X_PARTY (
	PARTY_ID INT64,
	FACILITY_ID INT64,
	Descriptor STRING(100),
	Code INT64,
	End_Date DATE,
	Start_date DATE,
	PARTY_FAC_CODE INT64,
) PRIMARY KEY (PARTY_ID, FACILITY_ID, Descriptor)
